# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ramiro García Poggi
# Description of the Site
description: My portfolio
# URL of Image of the Site
site-image: /assets/images/favicon.png
# Keywords of the Site
site-keywords: Ramiro Garcia Poggi, CV, Projects
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/IMG_6355.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: niunmango@yahoo.com
facebook_username: ramiro.garciapoggi
twitter_username: ramirogp
instagram_username: ramirogp
linkedin_username: ramirogp
github_username:  niunmango
youtube_channel_id: UCrKdapYS_2pUW1Lmczi14Xg
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-JCCRVBQ7ZL

# Disqus
disqus-shortname: ""

# Name of the Author
author-name: ramiroGarciaPoggi
# URL for the Image of the Author
author-image: /assets/images/me.jpg
# 60 Words About the Author
author-about: With a rich background as a solutions engineer, I bring to the table a comprehensive skill set that includes Kubernetes, Docker, Networking, Linux, Bash, IP, VoIP, CTI, WFM, Voice Recording, Quality Management, Video Recording, CRM, ERP, Sales, Technical Sales, and voice biometrics. My experience extends to system installation, administration, and management. I have a deep understanding of CRM and Contact Center software, coupled with a solid background in IT Support, networking, and telecommunications. I am fluent in Spanish and English, proficient in Italian and Portuguese.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://niunmango.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
